config/routes.rb
Rails.application.routes.draw do
  get '/home/index'
  get '/search', to: 'search#index', as: :search

  get '/creator/:creator_id', to: 'creators#show', as: :creator
  get '/design/:design_id', to: 'custom_designs#show', as: :custom_design
  get '/design/:design_id/edit', to: 'custom_designs#edit', as: :edit_custom_design
  patch '/design/:design_id', to: 'custom_designs#update'

  resources :custom_designs, only: %i[new create destroy], param: :design_id do
    collection do
      get '/unpublished', action: 'unpublished', as: :unpublished
    end

    member do
      put '/publish', action: 'publish', as: :publish
      put '/unpublish', action: 'unpublish', as: :unpublish
    end
  end

  resources :tags, only: :index

  root to: 'home#index'
end

app/models/custom_design.rb
class CustomDesign < ApplicationRecord
  include PgSearch::Model
  # CONFIGS
  pg_search_scope :search_by_everything,
    against: %i[full_text_index],
    using: { tsearch: { tsvector_column: :full_text_index } },
    ignoring: :accents

  # RELATIONS
  belongs_to :creator

  belongs_to :main_picture, class_name: 'Picture', autosave: true
  belongs_to :example_picture, class_name: 'Picture', autosave: true, optional: true

  has_many :categorizations, dependent: :destroy
  has_many :taggings, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :hearts, dependent: :destroy

  has_many :categories, through: :categorizations
  has_many :tags, through: :taggings

  accepts_nested_attributes_for :main_picture
  accepts_nested_attributes_for :example_picture, reject_if: proc { |attributes| attributes[:image].blank? }

  # VALIDATIONS
  validates :name, presence: true
  validates :design_id, presence: true
  validates :main_picture, presence: true

  validates :design_id, uniqueness: true

  validates :name, length: { maximum: 20 }

  validates :design_id, format: { with: /\AMO(?:-(?:[A-Z]|\d){4}){3}\z/ }

  # CALLBACKS
  after_save do
    main_picture.image_derivatives! if main_picture.image_changed?
  end

  before_save :generate_full_text_index

  def generate_full_text_index
    connection = self.class.connection
    sql = <<-SQL
      SELECT
        setweight(to_tsvector('simple', unaccent(#{connection.quote(name)})), 'A') ||
        setweight(to_tsvector('simple', unaccent(#{connection.quote(design_id)})), 'A') ||
        setweight(to_tsvector('simple', unaccent(#{connection.quote(creator.name.to_s)})), 'B') ||
        setweight(to_tsvector('simple', unaccent(#{connection.quote(creator.creator_id.to_s)})), 'B') ||
        setweight(to_tsvector('simple', unaccent(#{connection.quote(categories.map(&:name).join(' '))})), 'B') ||
        setweight(to_tsvector('simple', unaccent(#{connection.quote(tags.map(&:name).join(' '))})), 'B') AS full_text_index
    SQL

    result = self.class.connection.execute(self.class.sanitize_sql(sql))

    if result.any?
      self.full_text_index = result[0]['full_text_index']
    end
  end
end

app/controllers/custom_designs_controller.rb
class CustomDesignsController < ApplicationController
  before_action :require_admin, only: %i[unpublished edit update destroy publish unpublish]
  before_action :check_recaptcha, only: :create

  def unpublished
    scope = CustomDesign.unpublished

    @pagy, @custom_designs = pagy(scope)
  end

  def show
    @custom_design = find_custom_design
  end

  def new
    @custom_design = CustomDesign.new
    @custom_design.build_main_picture
    @custom_design.build_example_picture
    load_categories
  end

  def create
    @custom_design = CustomDesign.new(custom_design_params)
    @custom_design.published = current_admin.present?

    if @custom_design.save
      redirect_to @custom_design, success: 'Custom design created with success'
    else
      @custom_design.build_example_picture if @custom_design.example_picture.blank?
      load_categories
      render 'new'
    end
  end

  def edit
    @custom_design = find_custom_design
    @custom_design.build_example_picture if @custom_design.example_picture.blank?
    load_categories
  end

  def update
    @custom_design = find_custom_design

    if @custom_design.update(custom_design_params)
      redirect_to @custom_design, success: 'Custom design updated with success'
    else
      @custom_design.build_example_picture if @custom_design.example_picture.blank?
      load_categories
      render 'edit'
    end
  end

  def destroy
    @custom_design = CustomDesign.find_by!(design_id: params[:design_id])

    if @custom_design.destroy!
      options = { success: 'Custom design destroyed with success' }
    else
      options = { error: 'An error occurred' }
    end

    redirect_to custom_designs_path, options
  end

  def publish
    @custom_design = find_custom_design

    if @custom_design.update(published: true)
      redirect_to @custom_design, success: 'Custom Design was published'
    else
      redirect_back fallback_location: @custom_design, error: 'An error occurred'
    end
  end

  def unpublish
    @custom_design = find_custom_design

    if @custom_design.update(published: false)
      redirect_to @custom_design, success: 'Custom Design was unpublished'
    else
      redirect_back fallback_location: @custom_design, error: 'An error occurred'
    end
  end

  private
  def find_custom_design
    CustomDesign.find_by!(design_id: params[:design_id])
  end

  def check_recaptcha
    return if current_admin.present?

    validate_recaptcha!(token: params[:recaptcha_token], action: 'upload')
  end

  def load_categories
    @categories = Category.all
  end

  def custom_design_params
    raw_tags = params.require(:custom_design).delete(:tags)

    sanitized_params = params.require(:custom_design).permit(
      :name,
      :design_id,
      :creator_name,
      :creator_id,
      main_picture_attributes: %i[id image],
      example_picture_attributes: %i[id image],
      category_ids: []
    ).merge(tag_ids: handle_tag_ids(raw_tags))

    sanitized_params[:category_ids].reject!(&:blank?)
    sanitized_params
  end

  def handle_tag_ids(raw_tags)
    tag_names = JSON.parse(raw_tags).flat_map(&:values).reject(&:blank?)
    tags = tag_names.to_a.first(5).map do |name|
      tag = Tag.find_by('lower(unaccent(name)) = lower(unaccent(?))', name.strip)
      tag || Tag.create!(name: name.strip) rescue nil
    end
    tags.compact.map(&:id)
  rescue => e
    []
  end
end

app/views/custom_designs/_custom_design_card.html.slim
.card
  .card-image
    = link_to custom_design_path(custom_design) do
      figure.image.is-1-by1.custom-design-card-image
        = image_tag custom_design.main_picture.image(:thumbnail).url, alt: custom_design.name

  .card-content
    .media
      .media-content
        = link_to custom_design_path(custom_design) do
          p.title.is-4 = custom_design.name
          p.subtitle.is-6 = custom_design.design_id

        = link_to creator_path(custom_design.creator_id) do
          p.has-text-weight-bold.has-text-dark.is-4 = custom_design.creator_name

    .content
      .tags.is-small
        - custom_design.categories.each do |category|
          span.tag.is-dark.has-text-weight-semibold
            = link_to category.name, search_path(q: category.name), class: 'has-text-white'

        - custom_design.tags.each do |tag|
          span.tag.is-light
            = link_to tag.name, search_path(q: tag.name), class: 'has-text-black'

  - if current_admin.present?
    .card-footer
      - if custom_design.published?
        p.card-footer-item.has-text-centered
          = link_to unpublish_custom_design_path(custom_design),
            title: 'Click to unpublish',
            class: 'has-text-primary',
            method: :put do
            span.icon.is-small
              i.fas.fa-toggle-on
      - else
        p.card-footer-item.has-text-centered
          = link_to publish_custom_design_path(custom_design),
            title: 'Click to publish',
            class: 'has-text-danger',
            method: :put do
            span.icon.is-small
              i.fas.fa-toggle-off

      p.card-footer-item.has-text-centered
        = link_to edit_custom_design_path(custom_design), title: 'Edit', class: 'has-text-dark' do
          span.icon.is-small
            i.fas.fa-edit

      p.card-footer-item.has-text-centered
        = link_to custom_design_path(custom_design),
          method: :delete,
          data: { confirm: 'Are you sure?' },
          title: 'Destroy',
          class: 'has-text-danger has-text-centered' do
          span.icon.is-small
            i.fas.fa-trash

app/views/custom_designs/_form.html.slim
= form_for custom_design do |f|
  .field
    = f.label :name, 'Design Name', class: 'label'
    .control
      = f.text_field :name, class: 'input'
      = errors_for(custom_design, :name)

  .field
    = f.label :design_id,  'Design ID', class: 'label'
    .control
      = f.text_field :design_id, class: 'input'
      = errors_for(custom_design, :design_id)

  .field
    = f.label :creator_name,  'Creator', class: 'label'
    .control
      = f.text_field :creator_name, class: 'input'
      = errors_for(custom_design, :creator_name)

  .field
    = f.label :creator_id,  'Creator ID', class: 'label'
    .control
      = f.text_field :creator_id, class: 'input'
      = errors_for(custom_design, :creator_id)

  = f.fields_for :main_picture do |main_picture_form|
    .field
      .control
        .label
          | Custom Design Screenshot
        #main-picture-div.file.has-name.is-fullwidth
          label.file-label
            = main_picture_form.hidden_field :image, value: custom_design.main_picture.try(:cached_image_data)
            = main_picture_form.file_field :image, class: 'file-input', accept: '.png, .jpg, .jpeg'
            span.file-cta
              span.file-icon
                i.fas.fa-upload
              span.file-label.is-hidden-mobile Choose a image

            span.file-name.truncate = custom_design.main_picture.image_data.try(:dig, 'metadata', 'filename')

      = errors_for(custom_design.main_picture, :image)
      = errors_for(custom_design.main_picture, :image_data)

  = f.fields_for :example_picture do |example_picture_form|
    .field
      .control
        label.label
          | Usage Screenshot
          span.has-text-weight-light
            |  (optional)
        #example-picture-div.file.has-name.is-fullwidth
          label.file-label
            = example_picture_form.hidden_field :image, value: custom_design.example_picture.try(:cached_image_data)
            = example_picture_form.file_field :image, class: 'file-input', accept: '.png, .jpg, .jpeg'
            span.file-cta
              span.file-icon
                i.fas.fa-upload
              span.file-label.is-hidden-mobile Choose a image

            span.file-name.truncate = custom_design.example_picture.image_data.try(:dig, 'metadata', 'filename')
      = errors_for(custom_design.example_picture, :image)

  .field
    label.label Categories
    .control
      .select.is-multiple.is-fullwidth
        = f.collection_select :category_ids,
          @categories,
          :id,
          :name,
          {},
          multiple: true,
          include_blank: false,
          include_hidden: false

  .field
    label.label Tags
    .control
      = text_field_tag 'custom_design[tags]', custom_design.tags.map(&:name).join(', ')

  .field
    .control
      = f.submit class: 'button is-dark has-text-weight-bold has-text-white is-fullwidth'

  .field
    .control
      = link_to 'Back', custom_designs_path, class: 'button is-text is-fullwidth'

  = execute_recaptcha('upload')

- content_for :scripts
  = javascript_pack_tag 'custom_designs/form'

- content_for :recaptcha_js
  = include_recaptcha_js

app/views/custom_designs/edit.html.slim
.columns.is-centered
  .column.is-6
    .box
      .title Edit Custom Design

      = render 'form', custom_design: @custom_design

app/views/custom_designs/index.html.slim
.columns.is-centered
  .column.is-12
    .title My Custom Designs
    .subtitle = pluralize(@pagy.count, 'Custom Design')
.columns.is-multiline
  - if @custom_designs.exists?
    - @custom_designs.each do |custom_design|
      .column.is-one-quarter-widescreen.is-one-third-desktop.is-half-tablet.is-full-mobile
        = render 'custom_design_card', custom_design: custom_design

    .column.is-12
      == render 'layouts/pagination', pagy: @pagy

  - if @custom_designs.empty?
    .column.is-12
      .box.has-text-centered
        br
        .subtitle
          | You don't have any custom designs published yet. Create one
          =< link_to 'here', new_custom_design_path
          | .
        p

- content_for :scripts
  = javascript_pack_tag 'bookmark'
  = javascript_pack_tag 'heart'

app/views/custom_designs/new.html.slim
.columns.is-centered
  .column.is-6
    .box
      .title New Custom Design
      - if current_admin.blank?
        .content
          p Thanks for submitting a custom design. Some useful informations:
          ul
            li Don't do any cropping. We do it for you.
            li
              | Your custom design image should be like
              =<  link_to 'this', asset_pack_path('media/images/custom-design-example.jpg'), target: '_blank'
              | .
            li Use pictures shared directly from Nintendo Switch. It has the perfect resolution for our cropping.
            li Your custom design will be reviewed by us before being published.

      = render 'form', custom_design: @custom_design

app/views/custom_designs/show.html.slim
// METATAGS
- title = @custom_design.name
- description = @custom_design.design_id
- set_meta_tags 'og:title' => "#{@custom_design.name} - CustomDesigns.app"
- set_meta_tags 'og:site_name' => 'CustomDesigns.app'
- set_meta_tags 'og:image' => root_url.delete_suffix('/') + @custom_design.main_picture.image(:thumbnail).url
- set_meta_tags 'og:description' => "Check out #{@custom_design.name} Custom Design"
- set_meta_tags 'og:url' => custom_design_url(@custom_design)
- set_meta_tags 'twitter:card' => 'summary_large_image'

.columns.is-centered
  .column.is-8
    .box
      .columns.is-centered
        .column.is-3
          = image_tag @custom_design.main_picture.image(:thumbnail).url, class: 'image is-1-by1'

        .column.is-9
          .title.is-size-4-mobile
            = @custom_design.name
            .subtitle = @custom_design.design_id

            .subtitle
              span.has-text-weight-bold
                = link_to @custom_design.creator_name, creator_path(@custom_design.creator_id), class: 'has-text-dark'

              =< '(' + @custom_design.creator_id + ')'

          .tags
            - @custom_design.categories.each do |category|
              span.tag.is-dark.has-text-weight-semibold
                = link_to category.name, search_path(q: category.name), class: 'has-text-white'

            - @custom_design.tags.each do |tag|
              span.tag.is-light
                = link_to tag.name, search_path(q: tag.name), class: 'has-text-black'

          nav.level.is-mobile
            .level-left
              / don't remove .level-left

            .level-right
              - if current_admin.present?
                = link_to edit_custom_design_path(@custom_design), title: 'Edit', class: 'level-item has-text-dark' do
                  span.icon
                    i.fas.fa-edit

                = link_to custom_design_path(@custom_design),
                  method: :delete,
                  data: { confirm: 'Are you sure?' },
                  title: 'Destroy',
                  class: 'has-text-danger level-item' do
                  span.icon
                    i.fas.fa-trash

                - if @custom_design.published?
                  = link_to unpublish_custom_design_path(@custom_design),
                    title: 'Click to unpublish',
                    class: 'level-item has-text-primary',
                    method: :put do
                    span.icon
                      i.fas.fa-toggle-on
                - else
                  = link_to publish_custom_design_path(@custom_design),
                    title: 'Click to publish',
                    class: 'level-item has-text-danger',
                    method: :put do
                    span.icon
                      i.fas.fa-toggle-off

      - if @custom_design.example_picture.present?
        .column
          .subtitle Example:
          figure.image.is-16by9
            = image_tag @custom_design.example_picture.image_url, class: 'image is-16-by9'

- content_for :scripts
  = javascript_pack_tag 'bookmark'
  = javascript_pack_tag 'heart'

app/views/custom_designs/unpublished.slim
.columns.is-centered
  .column.is-12
    .title Unpublished Custom Designs
    .subtitle = pluralize(@pagy.count, 'Custom Design')

.columns.is-multiline
  - if @custom_designs.exists?
    - @custom_designs.each do |custom_design|
      .column.is-one-quarter-widescreen.is-one-third-desktop.is-half-tablet.is-full-mobile
        = render 'custom_design_card', custom_design: custom_design

    .column.is-12
      == render 'layouts/pagination', pagy: @pagy

  - if @custom_designs.empty?
    .column.is-12
      .box.has-text-centered
        br
        .subtitle
          | There aren't unpublished custom designs
        p