config/routes.rb
Rails.application.routes.draw do
  get '/home/index'
  get '/search', to: 'search#index', as: :search

  get '/creator/:creator_id', to: 'creators#show', as: :creator
  get '/design/:design_id', to: 'custom_designs#show', as: :custom_design
  get '/design/:design_id/edit', to: 'custom_designs#edit', as: :edit_custom_design
  patch '/design/:design_id', to: 'custom_designs#update'

  resources :custom_designs, only: %i[new create destroy], param: :design_id do
    collection do
      get '/unpublished', action: 'unpublished', as: :unpublished
    end

    member do
      put '/publish', action: 'publish', as: :publish
      put '/unpublish', action: 'unpublish', as: :unpublish
    end
  end

  resources :tags, only: :index

  root to: 'home#index'
end

app/models/creator.rb
class Creator < ApplicationRecord
  has_many :custom_designs, dependent: :destroy

  validates :name, presence: true, on: :update
  validates :creator_id, presence: true, on: :update

  validates :name, length: { maximum: 20 }

  validates :creator_id, format: { with: /\AMA(?:-(?:\d){4}){3}\z/ }, allow_blank: true

  after_save :generate_custom_designs_full_text_index

  def to_param
    creator_id
  end

  private

  def generate_custom_designs_full_text_index
    if saved_change_to_name? or saved_change_to_creator_id?
      custom_designs.each(&:save)
    end
  end
end

app/controllers/creators_controller.rb
class CreatorsController < ApplicationController
  def show
    custom_design_scope = CustomDesign.where(creator_id: params[:creator_id])
    @pagy, @custom_designs = pagy(custom_design_scope)

    raise ActiveRecord::RecordNotFound if @pagy.count == 0
  end
end

app/views/creators/show.html.slim
// METATAGS
- custom_design = @custom_designs.first
- creator_name = custom_design.creator_name
- creator_id = custom_design.creator_id

- title = creator_name
- description "Check out #{creator_name}'s Custom Designs"
- set_meta_tags 'og:title' => "#{creator_name} - CustomDesigns.app"
- set_meta_tags 'og:site_name' => 'CustomDesigns.app'
- set_meta_tags 'og:image' => image_url('preview.png')
- set_meta_tags 'og:description' => "Check out #{creator_name}'s Animal Crossing Custom Designs"
- set_meta_tags 'og:url' => creator_url(creator_id)
- set_meta_tags 'twitter:card' => 'summary_large_image'


.title = "#{creator_name} | #{creator_id}"
.subtitle = pluralize(@pagy.count, 'Custom Design')

.columns.is-multiline
  - @custom_designs.each do |custom_design|
    .column.is-one-quarter-widescreen.is-one-third-desktop.is-half-tablet.is-full-mobile
      = render 'custom_designs/custom_design_card', custom_design: custom_design

  .column.is-12
    = render 'layouts/pagination', pagy: @pagy