config/routes.rb
Rails.application.routes.draw do
  get '/home/index'
  get '/search', to: 'search#index', as: :search

  get '/creator/:creator_id', to: 'creators#show', as: :creator
  get '/design/:design_id', to: 'custom_designs#show', as: :custom_design
  get '/design/:design_id/edit', to: 'custom_designs#edit', as: :edit_custom_design
  patch '/design/:design_id', to: 'custom_designs#update'

  resources :custom_designs, only: %i[new create destroy], param: :design_id do
    collection do
      get '/unpublished', action: 'unpublished', as: :unpublished
    end

    member do
      put '/publish', action: 'publish', as: :publish
      put '/unpublish', action: 'unpublish', as: :unpublish
    end
  end

  resources :tags, only: :index

  root to: 'home#index'
end

app/views/layouts/_analytics.html.slim
script(async src="https://www.googletagmanager.com/gtag/js?id=#{analytics_id}")

javascript:
  window.dataLayer = window.dataLayer || [];
  function gtag () { dataLayer.push(arguments); };
  gtag('js', new Date());
  gtag('config', '#{analytics_id}');

app/views/layouts/_footer.html.slim
footer.footer
  .content.has-text-centered.has-text-white
    b <a href="https://www.patreon.com/stephann?fan_landing=true" class="has-text-white">Support me</a>.
    b =< link_to 'Open source', 'https://github.com/stephannv/customdesigns', target: '_blank', class: 'has-text-white'

app/views/layouts/_navbar.html.slim
nav.navbar.is-primary.is-fixed-top(role='navigation' aria-label='main navigation')
  .navbar-brand
    .container.is-hidden-desktop
      = render 'layouts/navbar_search', classes: ''

    = link_to root_path, class: 'navbar-item is-hidden-touch' do
      = image_tag asset_pack_path('media/images/logo.svg')

    a.navbar-burger.burger(role='button' aria-label='menu' aria-expanded='false' data-target='navbarMenu')
      span(aria-hidden='true')
      span(aria-hidden='true')
      span(aria-hidden='true')


  .container.is-hidden-touch
    = render 'layouts/navbar_search', classes: ''
  #navbarMenu.navbar-menu

    .navbar-end
      = link_to root_path, class: 'navbar-item has-text-weight-semibold' do
        span.icon
          i.fas.fa-home
        | Home

      = link_to new_custom_design_path, class: 'navbar-item has-text-weight-semibold' do
        span.icon
          i.fas.fa-upload
        | Submit Custom Design

      = link_to 'https://www.patreon.com/stephann?fan_landing=true',
        class: 'navbar-item has-text-weight-semibold',
        target: '_blank' do
        span.icon
          i.fas.fa-heart
        | Support me

      - if current_admin.present?
        .navbar-item.has-dropdown.is-hoverable
          a.navbar-link.has-text-weight-semibold Admin

          .navbar-dropdown.is-right
            = link_to unpublished_custom_designs_path, class: 'navbar-item' do
              span.icon
                i.fas.fa-toggle-off
              | Unpublished Custom Design

            hr.navbar-divider
            = link_to sign_out_path, method: :delete, class: 'navbar-item' do
              span.icon
                i.fas.fa-sign-out-alt
              | Sign Out

app/views/layouts/_navbar_search.slim
.container(class=classes)
  = form_tag search_path, method: :get
    .navbar-item
      .field.navbar-search-input
        .control.has-icons-left.is-expanded
          = text_field_tag :q, @search_term,
            class: 'input is-fullwidth is-medium',
            placeholder: 'Name, id, category, tag, creator',
            autocomplete: 'off'

          span.icon
            i.fas.fa-search

app/views/layouts/_pagination.html.slim
- link = pagy_link_proc(pagy)

nav.pagination.is-medium(role='navigation' aria-label='pagination')
  - if pagy.prev
    == link.call(pagy.prev, pagy_t('pagy.nav.prev'), 'class="pagination-previous button" aria-label="previous page"')
  - else
    a.button.pagination-previous(disabled='disabled') == pagy_t('pagy.nav.prev')

  - if pagy.next
    == link.call(pagy.next, pagy_t('pagy.nav.next'), 'class="pagination-next button" aria-label="next page"')
  - else
    a.button.pagination-next(disabled='disabled') == pagy_t('pagy.nav.next')

  ul.pagination-list
    - pagy.series.each do |item|                 # series example: [1, :gap, 7, 8, "9", 10, 11, :gap, 36]
      - if item.is_a?(Integer)                   # page link
        li == link.call item, item, %(class="pagination-link" aria-label="goto page #{item}")

      - elsif item.is_a?(String)                 # current page
        li == link.call item, item, %(class="pagination-link is-current" aria-label="page #{item}" aria-current="page")

      - elsif item == :gap                       # page gap
        li
          span.pagination-ellipsis == pagy_t('pagy.nav.gap')

app/views/layouts/_recaptcha.html.slim
input(name='recaptcha_token' type='hidden' id=recaptcha_id)

javascript:
  const siteKey = '#{site_key}';
  const action = '#{action}';
  const tokenId = '#{recaptcha_id}';

  grecaptcha.ready(() => {
    grecaptcha.execute(siteKey, { action: action }).then((token) => {
      document.getElementById(tokenId).value = token
    })
  })

app/views/layouts/application.html.slim
doctype html
html.has-navbar-fixed-top
  head
    = csrf_meta_tags
    = csp_meta_tag

    meta(name='viewport' content='width=device-width, initial-scale=1')

    = javascript_pack_tag 'application'
    = stylesheet_pack_tag 'application'
    = stylesheet_link_tag 'application', media: 'all'
    = yield :recaptcha_js

    = display_meta_tags site: 'CustomDesigns.app'
  body.app
    = render 'layouts/navbar'
    .section.is-marginless.app-content
      .container
        = flash_message
        = yield

    = render 'layouts/footer'

  = yield :scripts
  = include_analytics_js